name: CI Testing
on:
  push:
    branches:
      - "*"
  pull_request:
    types: ['opened']
jobs:

  tests-pw-default-image: 
    name: 'Run Playwright on default image'
    runs-on: ubuntu-latest
    container:
     image: mcr.microsoft.com/playwright:v1.52.0
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./Lesson-30
        run: npm ci
      - name: Run e2e tests
        working-directory: ./Lesson-30
        env:
          TESTOMATIO: ${{ vars.TESTOMATIO }}
          TESTOMATIO_CREATE: ${{ vars.TESTOMATIO_CREATE }}
        run: npm run test:firefox
              

     

  